version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 50s
      retries: 20
    volumes:
      - pg_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: tz_aiti_guru
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    command: >
      sh -c "
      cd /app &&
      alembic upgrade head &&
      python main.py
      "

volumes:
  pg_data:
