"""init

Revision ID: 3b59ea03d7ae
Revises:

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3b59ea03d7ae"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("name", sa.String(length=512), nullable=False),
        sa.Column("parent_categories_id", sa.Integer(), nullable=True),
        sa.Column("materialize_path", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_categories_id"],
            ["categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("materialize_path"),
    )
    op.create_table(
        "clients",
        sa.Column("name", sa.String(length=512), nullable=False),
        sa.Column("address", sa.String(length=512), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "nomenclature",
        sa.Column("name", sa.String(length=512), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("cost", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("categories_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["categories_id"],
            ["categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "orders",
        sa.Column("clients_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_date", sa.DateTime(), server_default="NOW()", nullable=False
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["clients_id"],
            ["clients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "orders2nomenclature",
        sa.Column("orders_id", sa.Integer(), nullable=False),
        sa.Column("nomenclature_id", sa.Integer(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["nomenclature_id"],
            ["nomenclature.id"],
        ),
        sa.ForeignKeyConstraint(
            ["orders_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("orders_id", "nomenclature_id", "id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("orders2nomenclature")
    op.drop_table("orders")
    op.drop_table("nomenclature")
    op.drop_table("clients")
    op.drop_table("categories")
    # ### end Alembic commands ###
