-- Categories
INSERT INTO categories (name, parent_categories_id, materialize_path)
VALUES ('root', NULL, NULL);
INSERT INTO categories (name, parent_categories_id, materialize_path)
VALUES ('a', 1, '1');
INSERT INTO categories (name, parent_categories_id, materialize_path)
VALUES ('b', 1, '2');

INSERT INTO categories (name, parent_categories_id, materialize_path)
VALUES ('aa', 2, '1.1');
INSERT INTO categories (name, parent_categories_id, materialize_path)
VALUES ('ab', 2, '1.2');

INSERT INTO categories (name, parent_categories_id, materialize_path)
VALUES ('ba', 3, '2.1');
INSERT INTO categories (name, parent_categories_id, materialize_path)
VALUES ('bb', 3, '2.2');


-- Nomenclature
INSERT INTO nomenclature (name, count, cost, categories_id) VALUES ('nom_1', 10, 100.00, 2);
INSERT INTO nomenclature (name, count, cost, categories_id) VALUES ('nom_2', 5, 150.50, 2);
INSERT INTO nomenclature (name, count, cost, categories_id) VALUES ('nom_3', 20, 75.00, 2);
INSERT INTO nomenclature (name, count, cost, categories_id) VALUES ('nom_4', 8, 210.00, 2);
INSERT INTO nomenclature (name, count, cost, categories_id) VALUES ('nom_5', 12, 50.00, 3);
INSERT INTO nomenclature (name, count, cost, categories_id) VALUES ('nom_6', 7, 300.90, 3);
INSERT INTO nomenclature (name, count, cost, categories_id) VALUES ('nom_7', 15, 99.99, 3);
INSERT INTO nomenclature (name, count, cost, categories_id) VALUES ('nom_8', 3, 500.00, 3);
INSERT INTO nomenclature (name, count, cost, categories_id) VALUES ('nom_9', 6, 120.00, 4);
INSERT INTO nomenclature (name, count, cost, categories_id) VALUES ('nom_10', 9, 44.50, 4);
INSERT INTO nomenclature (name, count, cost, categories_id) VALUES ('nom_11', 11, 250.00, 4);
INSERT INTO nomenclature (name, count, cost, categories_id) VALUES ('nom_12', 4, 80.00, 5);
INSERT INTO nomenclature (name, count, cost, categories_id) VALUES ('nom_13', 14, 145.75, 5);
INSERT INTO nomenclature (name, count, cost, categories_id) VALUES ('nom_14', 2, 600.00, 5);
INSERT INTO nomenclature (name, count, cost, categories_id) VALUES ('nom_15', 7, 33.00, 6);
INSERT INTO nomenclature (name, count, cost, categories_id) VALUES ('nom_16', 10, 90.00, 6);
INSERT INTO nomenclature (name, count, cost, categories_id) VALUES ('nom_17', 5, 270.30, 6);
INSERT INTO nomenclature (name, count, cost, categories_id) VALUES ('nom_18', 9, 199.00, 7);
INSERT INTO nomenclature (name, count, cost, categories_id) VALUES ('nom_19', 13, 55.55, 7);
INSERT INTO nomenclature (name, count, cost, categories_id) VALUES ('nom_20', 1, 999.99, 7);


-- Clients
INSERT INTO clients (name, address) VALUES ('client_1', 'addr_1');
INSERT INTO clients (name, address) VALUES ('client_2', 'addr_2');
INSERT INTO clients (name, address) VALUES ('client_3', 'addr_3');
INSERT INTO clients (name, address) VALUES ('client_4', 'addr_4');
INSERT INTO clients (name, address) VALUES ('client_5', 'addr_5');


-- orders and m2m
INSERT INTO orders (clients_id, created_date) VALUES (5, '2025-10-03 08:23:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (1, 6, 7);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (1, 9, 9);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (1, 13, 1);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (1, 8, 3);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (1, 5, 7);
INSERT INTO orders (clients_id, created_date) VALUES (2, '2025-10-05 20:14:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (2, 3, 9);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (2, 1, 10);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (2, 11, 9);
INSERT INTO orders (clients_id, created_date) VALUES (2, '2025-10-17 18:52:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (3, 2, 5);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (3, 3, 4);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (3, 13, 9);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (3, 1, 2);
INSERT INTO orders (clients_id, created_date) VALUES (2, '2025-10-16 00:49:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (4, 19, 6);
INSERT INTO orders (clients_id, created_date) VALUES (1, '2025-10-13 18:16:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (5, 19, 9);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (5, 15, 8);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (5, 7, 10);
INSERT INTO orders (clients_id, created_date) VALUES (3, '2025-10-05 16:00:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (6, 19, 3);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (6, 18, 6);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (6, 10, 3);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (6, 9, 5);
INSERT INTO orders (clients_id, created_date) VALUES (5, '2025-09-30 19:48:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (7, 18, 4);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (7, 13, 3);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (7, 17, 3);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (7, 11, 6);
INSERT INTO orders (clients_id, created_date) VALUES (5, '2025-10-27 00:59:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (8, 8, 6);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (8, 13, 6);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (8, 15, 9);
INSERT INTO orders (clients_id, created_date) VALUES (1, '2025-10-14 23:02:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (9, 19, 6);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (9, 20, 9);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (9, 15, 8);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (9, 14, 6);
INSERT INTO orders (clients_id, created_date) VALUES (3, '2025-10-27 05:54:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (10, 13, 2);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (10, 16, 1);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (10, 11, 6);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (10, 6, 7);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (10, 12, 7);
INSERT INTO orders (clients_id, created_date) VALUES (2, '2025-10-20 01:40:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (11, 11, 6);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (11, 18, 5);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (11, 12, 7);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (11, 3, 7);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (11, 17, 4);
INSERT INTO orders (clients_id, created_date) VALUES (4, '2025-10-16 05:38:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (12, 13, 8);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (12, 18, 6);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (12, 3, 10);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (12, 19, 6);
INSERT INTO orders (clients_id, created_date) VALUES (2, '2025-10-21 20:01:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (13, 20, 6);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (13, 16, 4);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (13, 4, 2);
INSERT INTO orders (clients_id, created_date) VALUES (3, '2025-10-09 00:38:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (14, 2, 4);
INSERT INTO orders (clients_id, created_date) VALUES (2, '2025-09-30 00:48:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (15, 5, 6);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (15, 6, 1);
INSERT INTO orders (clients_id, created_date) VALUES (5, '2025-10-17 03:22:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (16, 6, 1);
INSERT INTO orders (clients_id, created_date) VALUES (1, '2025-10-11 00:13:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (17, 14, 6);
INSERT INTO orders (clients_id, created_date) VALUES (5, '2025-09-30 22:05:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (18, 19, 3);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (18, 1, 3);
INSERT INTO orders (clients_id, created_date) VALUES (5, '2025-10-04 16:31:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (19, 1, 5);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (19, 5, 5);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (19, 12, 9);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (19, 14, 2);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (19, 8, 4);
INSERT INTO orders (clients_id, created_date) VALUES (5, '2025-10-27 03:50:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (20, 14, 10);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (20, 9, 3);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (20, 13, 2);
INSERT INTO orders (clients_id, created_date) VALUES (4, '2025-09-30 04:24:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (21, 17, 7);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (21, 2, 2);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (21, 9, 3);
INSERT INTO orders (clients_id, created_date) VALUES (1, '2025-10-02 15:23:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (22, 1, 6);
INSERT INTO orders (clients_id, created_date) VALUES (4, '2025-10-05 10:29:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (23, 17, 6);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (23, 20, 1);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (23, 2, 4);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (23, 13, 3);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (23, 15, 6);
INSERT INTO orders (clients_id, created_date) VALUES (5, '2025-10-03 02:59:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (24, 2, 4);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (24, 5, 10);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (24, 14, 2);
INSERT INTO orders (clients_id, created_date) VALUES (5, '2025-10-10 22:03:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (25, 7, 5);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (25, 2, 8);
INSERT INTO orders (clients_id, created_date) VALUES (5, '2025-10-24 06:43:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (26, 11, 1);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (26, 9, 7);
INSERT INTO orders (clients_id, created_date) VALUES (2, '2025-10-20 15:30:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (27, 3, 9);
INSERT INTO orders (clients_id, created_date) VALUES (1, '2025-10-02 16:37:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (28, 13, 9);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (28, 11, 9);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (28, 4, 7);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (28, 20, 3);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (28, 8, 9);
INSERT INTO orders (clients_id, created_date) VALUES (4, '2025-10-24 15:03:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (29, 2, 3);
INSERT INTO orders (clients_id, created_date) VALUES (2, '2025-10-15 07:02:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (30, 7, 8);
INSERT INTO orders (clients_id, created_date) VALUES (1, '2025-10-14 08:34:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (31, 12, 5);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (31, 2, 2);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (31, 15, 6);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (31, 11, 10);
INSERT INTO orders (clients_id, created_date) VALUES (1, '2025-10-04 05:30:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (32, 20, 3);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (32, 16, 2);
INSERT INTO orders (clients_id, created_date) VALUES (3, '2025-10-30 08:33:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (33, 17, 8);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (33, 11, 3);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (33, 5, 8);
INSERT INTO orders (clients_id, created_date) VALUES (1, '2025-10-17 15:26:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (34, 20, 4);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (34, 16, 7);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (34, 19, 5);
INSERT INTO orders (clients_id, created_date) VALUES (3, '2025-10-28 04:46:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (35, 16, 8);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (35, 15, 9);
INSERT INTO orders (clients_id, created_date) VALUES (3, '2025-09-29 13:20:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (36, 11, 10);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (36, 7, 6);
INSERT INTO orders (clients_id, created_date) VALUES (4, '2025-10-06 08:19:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (37, 12, 4);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (37, 16, 8);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (37, 19, 4);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (37, 10, 2);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (37, 3, 3);
INSERT INTO orders (clients_id, created_date) VALUES (5, '2025-10-24 00:16:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (38, 5, 10);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (38, 12, 9);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (38, 17, 6);
INSERT INTO orders (clients_id, created_date) VALUES (4, '2025-10-29 05:51:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (39, 14, 6);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (39, 3, 4);
INSERT INTO orders (clients_id, created_date) VALUES (2, '2025-10-15 23:20:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (40, 4, 2);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (40, 8, 6);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (40, 19, 1);
INSERT INTO orders (clients_id, created_date) VALUES (2, '2025-10-08 02:51:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (41, 3, 7);
INSERT INTO orders (clients_id, created_date) VALUES (3, '2025-10-09 22:50:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (42, 5, 9);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (42, 7, 1);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (42, 8, 9);
INSERT INTO orders (clients_id, created_date) VALUES (4, '2025-10-21 14:04:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (43, 11, 7);
INSERT INTO orders (clients_id, created_date) VALUES (2, '2025-10-24 04:42:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (44, 10, 2);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (44, 18, 3);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (44, 4, 5);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (44, 15, 5);
INSERT INTO orders (clients_id, created_date) VALUES (1, '2025-10-25 20:45:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (45, 17, 2);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (45, 11, 4);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (45, 7, 8);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (45, 1, 8);
INSERT INTO orders (clients_id, created_date) VALUES (3, '2025-10-19 12:36:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (46, 19, 2);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (46, 6, 10);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (46, 8, 3);
INSERT INTO orders (clients_id, created_date) VALUES (3, '2025-10-09 05:48:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (47, 12, 10);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (47, 1, 7);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (47, 2, 8);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (47, 7, 3);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (47, 8, 1);
INSERT INTO orders (clients_id, created_date) VALUES (2, '2025-09-30 10:47:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (48, 18, 9);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (48, 3, 2);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (48, 8, 10);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (48, 5, 1);
INSERT INTO orders (clients_id, created_date) VALUES (3, '2025-10-05 22:55:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (49, 3, 7);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (49, 20, 4);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (49, 16, 3);
INSERT INTO orders (clients_id, created_date) VALUES (1, '2025-10-28 17:32:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (50, 9, 1);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (50, 15, 6);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (50, 3, 6);
INSERT INTO orders (clients_id, created_date) VALUES (3, '2025-10-19 10:08:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (51, 3, 2);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (51, 20, 2);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (51, 7, 3);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (51, 11, 3);
INSERT INTO orders (clients_id, created_date) VALUES (3, '2025-10-03 11:05:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (52, 12, 1);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (52, 1, 4);
INSERT INTO orders (clients_id, created_date) VALUES (2, '2025-10-25 21:26:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (53, 6, 8);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (53, 7, 9);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (53, 19, 1);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (53, 14, 8);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (53, 11, 7);
INSERT INTO orders (clients_id, created_date) VALUES (5, '2025-10-12 20:23:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (54, 18, 9);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (54, 11, 6);
INSERT INTO orders (clients_id, created_date) VALUES (4, '2025-10-13 17:46:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (55, 6, 2);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (55, 2, 9);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (55, 11, 4);
INSERT INTO orders (clients_id, created_date) VALUES (1, '2025-10-21 11:48:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (56, 4, 1);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (56, 10, 10);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (56, 15, 5);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (56, 17, 10);
INSERT INTO orders (clients_id, created_date) VALUES (1, '2025-10-19 20:28:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (57, 19, 3);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (57, 2, 10);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (57, 8, 7);
INSERT INTO orders (clients_id, created_date) VALUES (5, '2025-10-25 15:25:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (58, 5, 7);
INSERT INTO orders (clients_id, created_date) VALUES (2, '2025-10-23 12:44:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (59, 14, 10);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (59, 2, 4);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (59, 10, 7);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (59, 17, 3);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (59, 3, 1);
INSERT INTO orders (clients_id, created_date) VALUES (3, '2025-10-19 05:13:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (60, 6, 8);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (60, 12, 6);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (60, 16, 3);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (60, 13, 8);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (60, 11, 4);
INSERT INTO orders (clients_id, created_date) VALUES (1, '2025-10-14 20:42:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (61, 18, 1);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (61, 1, 9);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (61, 19, 4);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (61, 13, 5);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (61, 5, 5);
INSERT INTO orders (clients_id, created_date) VALUES (3, '2025-10-28 18:53:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (62, 15, 1);
INSERT INTO orders (clients_id, created_date) VALUES (5, '2025-10-21 13:31:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (63, 5, 9);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (63, 13, 6);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (63, 4, 1);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (63, 3, 7);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (63, 12, 7);
INSERT INTO orders (clients_id, created_date) VALUES (2, '2025-10-17 18:41:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (64, 8, 10);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (64, 7, 1);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (64, 15, 9);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (64, 14, 6);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (64, 3, 2);
INSERT INTO orders (clients_id, created_date) VALUES (1, '2025-10-17 02:29:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (65, 17, 9);
INSERT INTO orders (clients_id, created_date) VALUES (2, '2025-10-07 17:30:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (66, 16, 7);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (66, 8, 10);
INSERT INTO orders (clients_id, created_date) VALUES (5, '2025-10-02 17:10:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (67, 20, 4);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (67, 17, 5);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (67, 3, 9);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (67, 13, 6);
INSERT INTO orders (clients_id, created_date) VALUES (1, '2025-10-13 15:11:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (68, 19, 9);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (68, 8, 3);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (68, 18, 8);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (68, 15, 2);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (68, 1, 8);
INSERT INTO orders (clients_id, created_date) VALUES (4, '2025-10-28 18:27:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (69, 8, 4);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (69, 15, 4);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (69, 10, 7);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (69, 14, 2);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (69, 9, 9);
INSERT INTO orders (clients_id, created_date) VALUES (2, '2025-09-30 05:16:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (70, 14, 10);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (70, 10, 9);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (70, 15, 10);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (70, 16, 7);
INSERT INTO orders (clients_id, created_date) VALUES (4, '2025-10-15 21:04:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (71, 18, 5);
INSERT INTO orders (clients_id, created_date) VALUES (1, '2025-10-10 06:49:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (72, 14, 5);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (72, 3, 7);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (72, 18, 4);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (72, 12, 8);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (72, 13, 2);
INSERT INTO orders (clients_id, created_date) VALUES (4, '2025-10-21 16:16:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (73, 6, 4);
INSERT INTO orders (clients_id, created_date) VALUES (5, '2025-10-01 07:20:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (74, 12, 3);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (74, 11, 6);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (74, 6, 7);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (74, 10, 5);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (74, 17, 4);
INSERT INTO orders (clients_id, created_date) VALUES (3, '2025-10-19 13:15:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (75, 9, 1);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (75, 12, 4);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (75, 18, 3);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (75, 2, 4);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (75, 19, 5);
INSERT INTO orders (clients_id, created_date) VALUES (3, '2025-10-14 12:27:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (76, 5, 1);
INSERT INTO orders (clients_id, created_date) VALUES (1, '2025-10-25 06:40:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (77, 11, 3);
INSERT INTO orders (clients_id, created_date) VALUES (5, '2025-10-04 03:49:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (78, 7, 1);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (78, 13, 5);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (78, 12, 4);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (78, 10, 8);
INSERT INTO orders (clients_id, created_date) VALUES (3, '2025-10-27 23:06:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (79, 10, 7);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (79, 8, 8);
INSERT INTO orders (clients_id, created_date) VALUES (3, '2025-10-08 09:47:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (80, 15, 10);
INSERT INTO orders (clients_id, created_date) VALUES (1, '2025-10-04 18:52:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (81, 11, 4);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (81, 17, 2);
INSERT INTO orders (clients_id, created_date) VALUES (4, '2025-10-24 21:54:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (82, 20, 3);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (82, 19, 3);
INSERT INTO orders (clients_id, created_date) VALUES (5, '2025-10-29 16:40:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (83, 4, 1);
INSERT INTO orders (clients_id, created_date) VALUES (5, '2025-10-15 13:03:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (84, 14, 2);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (84, 19, 1);
INSERT INTO orders (clients_id, created_date) VALUES (5, '2025-10-04 21:05:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (85, 7, 4);
INSERT INTO orders (clients_id, created_date) VALUES (1, '2025-10-14 05:19:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (86, 16, 10);
INSERT INTO orders (clients_id, created_date) VALUES (3, '2025-10-20 03:26:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (87, 14, 9);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (87, 19, 7);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (87, 16, 10);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (87, 2, 1);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (87, 8, 1);
INSERT INTO orders (clients_id, created_date) VALUES (2, '2025-09-29 18:26:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (88, 19, 4);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (88, 18, 2);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (88, 15, 6);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (88, 3, 2);
INSERT INTO orders (clients_id, created_date) VALUES (4, '2025-10-21 13:13:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (89, 2, 9);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (89, 14, 6);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (89, 11, 4);
INSERT INTO orders (clients_id, created_date) VALUES (2, '2025-10-11 01:58:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (90, 14, 4);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (90, 20, 6);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (90, 18, 2);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (90, 2, 8);
INSERT INTO orders (clients_id, created_date) VALUES (3, '2025-10-17 21:31:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (91, 10, 9);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (91, 13, 5);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (91, 4, 9);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (91, 3, 7);
INSERT INTO orders (clients_id, created_date) VALUES (5, '2025-10-28 03:32:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (92, 15, 1);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (92, 11, 10);
INSERT INTO orders (clients_id, created_date) VALUES (3, '2025-10-03 14:31:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (93, 7, 5);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (93, 8, 4);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (93, 11, 3);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (93, 6, 10);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (93, 12, 4);
INSERT INTO orders (clients_id, created_date) VALUES (1, '2025-10-13 05:59:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (94, 4, 9);
INSERT INTO orders (clients_id, created_date) VALUES (2, '2025-10-11 07:25:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (95, 4, 7);
INSERT INTO orders (clients_id, created_date) VALUES (2, '2025-10-28 06:01:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (96, 20, 9);
INSERT INTO orders (clients_id, created_date) VALUES (5, '2025-10-02 04:47:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (97, 9, 5);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (97, 1, 10);
INSERT INTO orders (clients_id, created_date) VALUES (3, '2025-10-05 08:35:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (98, 3, 6);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (98, 12, 1);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (98, 6, 6);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (98, 15, 10);
INSERT INTO orders (clients_id, created_date) VALUES (3, '2025-10-06 14:03:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (99, 6, 2);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (99, 15, 2);
INSERT INTO orders (clients_id, created_date) VALUES (5, '2025-10-19 23:27:09');
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (100, 3, 8);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (100, 6, 3);
INSERT INTO orders2nomenclature (orders_id, nomenclature_id, count) VALUES (100, 7, 6);
